### ISSUE TITLE
Ulimit test fails in few cases

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#10]
Ulimit test fails in few cases even when high ulimits are set. Verify the logic

**Comment by jamestyj** [comment]
@manojsundaram Please always provide an example/test case so that the issue can be reproduced.

**Comment by robgajudo** [comment]
Tried the scripts in RHEL 7.2.

ulimits is pointed to /etc/security/limits.d/* wherein the config file for the limits.conf is located in /etc/security/limits.conf
