### ISSUE TITLE
Bare metal vs VM check does not work on CentOS/RHEL6

### ISSUE THREAD

**Issue by dbeech** [cloudera-ps/prereq-checks#131]
The `systemd-detect-virt` command used by the check does not exist on RHEL or CentOS 6. 
```
./prereq-check.sh: line 1259: systemd-detect-virt: command not found
```

**Comment by melvin-koh** [comment]
CDP is not supported for RHEL/CentOS 6, so there is no point to adding checks for RHEL/CentOS 6 now.
