### ISSUE TITLE
Fix free memory report

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#15]
currently, the system information reports the free memory using the following block of code:
function print_cpu_and_ram() {
  local cpu=`grep -m1 "^model name" /proc/cpuinfo | cut -d' ' -f3- | sed -e 's/(R)//' -e 's/Core(TM) //' -e 's/CPU //'`
  print_label "CPUs" "`nproc`x $cpu"
  print_label "RAM" "`awk '/MemTotal:/ {printf "%d GB", $2/1000/1000}' /proc/meminfo`"
}

This calculation is incorrect and will show incorrect numbers. one example is:
RAM:           263 GB

The result from "free -g" is more accurate and unit conversion is already done.

**Comment by jamestyj** [comment]
Agree that using `free` is better. However, looks like `free -h` is best:

```
[vagrant@centos7 prereq-checks]$ free -g
              total        used        free      shared  buff/cache   available
Mem:              3           0           3           0           0           3
Swap:             1           0           1
[vagrant@centos7 prereq-checks]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.7G        111M        3.0G        8.8M        592M        3.4G
Swap:          2.0G          0B        2.0G
```

**Comment by kmizumar** [comment]
We just need to know how much RAM the server has. No need to display the memory usage, etc. Closing this issue as won't fix.
