### ISSUE TITLE
Use base 1024 instead of 1000 for memory report

### ISSUE THREAD

**Issue by myloginid** [cloudera-ps/prereq-checks#28]
This number does not match with whats reported in CSI
` print_label "RAM" "`awk '/MemTotal:/ {printf "%d GB", $2/1000/1000}' /proc/meminfo` `

**Comment by kmizumar** [comment]
wait for a review of pull request https://github.com/cloudera-ps/prereq-checks/pull/33 for this issue.

**Comment by kmizumar** [comment]
hmm, this issue conflicts with #34 Fix free memory report.

**Comment by kmizumar** [comment]
solved with pull request #35 
no need to calculate total RAM size by ourself. free command will do it.
