### ISSUE TITLE
Database check fails on the version of mysql-connector-java

### ISSUE THREAD

**Issue by sjjohansen** [cloudera-ps/prereq-checks#57]
The function `check_database` currently fails if the first line returned from `rpm -qa` is `mysql-connector-java-*`. 

```
 FAIL  Database: Supported MySQL server installed. Actual: mysql-connector-java-5.1.25
```

This seems to be because the package major version is checked as 5.1 and this doesn't match either 5.5 or 5.6.

At the same time it's probably worth adding 5.7 as a supported version of MySQL as that seems to have been true at least since CDH 5.10

**Comment by kmizumar** [comment]
Here is the current implementation of check_database function: 

```
function check_database() {
  local mysql=`echo "$RPM_QA" | egrep -v "mysql-community-(common|libs|client)-" | egrep -v "mysql-(common|libs|client)-" | grep -m1 "^mysql-"`
  if [ "$mysql" ]; then
    local ver=`echo $mysql | cut -d'-' -f1-4`
  else
    state "Database: MySQL server not installed, skipping version check" 2
    return
  fi

  local major_ver=`echo $ver | cut -d'-' -f4 | cut -d'.' -f1-2`
  local msg="Database: Supported MySQL server installed. Actual: $ver"
  if [ "$major_ver" = "5.5" ] || [ "$major_ver" = "5.6" ]; then
    state "$msg" 0
  else
    state "$msg" 1
  fi
}
```

This seems completely wrong and useless for me. I'll re-write this later.

**Comment by kmizumar** [comment]
Got a list of files for MySQL Enterprise Edition. It seems that checking `mysql-community-server` or `mysql-commercial-server` package is enough.

<img width="661" alt="upload" src="https://user-images.githubusercontent.com/226835/28176860-d8b11e50-6833-11e7-924c-cff15a0da6be.png">

**Comment by kmizumar** [comment]
Pull request #64 Fix MySQL server check will solve this.

**Comment by kmizumar** [comment]
Pull request #64 Fix MySQL server check is merged.
