### ISSUE TITLE
Make the script work on RHEL 7 as good as it does on RHEL 6

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#8]
Make the script work on RHEL 7 as good as it does on RHEL 6. Update the readme accordingly.

**Comment by kmizumar** [comment]
Please check the two outputs from CentOS 7.3 and CentOS 6.8. Does this look good enough for you? I feel issue description is too vague.
https://gist.github.com/kmizumar/866ae934a8aaf0a32f05ce997bf2d7de

**Comment by jhshin9** [comment]
@kmizumar @jamestyj  @manojsundaram This issue is too broad. I think we should close this issue and register it as a more detailed issue.

**Comment by jamestyj** [comment]
Yes agreed, that's the same as what I had discussed with Maru yesterday.
With the recent commits, RHEL 7 support should be complete. Otherwise
please file specific issues.
