### ISSUE TITLE
checks.sh throw errors when dig is not installed

### ISSUE THREAD

**Issue by melvin-koh** [cloudera-ps/prereq-checks#81]
Ran the scripts on a fresh vanilla CentOS 7.2 machine and throw an error that dig command is not found:
```
/root/prereq-checks-master/lib/checks.sh: line 360: dig: command not found
/root/prereq-checks-master/lib/checks.sh: line 361: dig: command not found
 FAIL  Network: Consistent name resolution of meltest-2.gce.cloudera.com
```

Think it may be more elegant to check for the existence of dig command and report appropriate message that command is not installed?

**Comment by manojsundaram** [comment]
+1, closing this issue. and opening a broader issue (#82) that will address #81 and more.

Thanks for reporting this @melvin-koh

**Comment by jamestyj** [comment]
Agree with @melvin-koh that the script should check for such dependencies instead of solely relying on the README.

**Comment by jamestyj** [comment]
Fixed.
