### ISSUE TITLE
Improve security prereqs README

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#82]
When the security prereq was merged into the deployment, all README stuff was not merged. This includes some critical information like missing packages required for the script to work - perl-Convert-ASN1, bind-utils.

This ties back to the issue that @melvin-koh submitted at #81

**Comment by manojsundaram** [comment]
Instructions are available at "clouderasecurity-prereq", internal github repo

**Comment by jamestyj** [comment]
I've add the steps to install the dependencies to the README. However we will need to polish up the security prereqs related README - e.g. what it does, screenshot examples, recommended usage (e.g. can run just from one node).
