### ISSUE TITLE
Revamp the toolkit and make easier for new-users to onboard

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#83]
Filing this after discussing with James
1. Should cleanup the README and make it easier to understand and read
2. See if a reshuffling of file locations, changing file names is required

Will add more info on this issue as i collect feedback, info from rest of the userbase

**Comment by jamestyj** [comment]
> 2. See if a reshuffling of file locations, changing file names is required

I've done some refactoring yesterday, in particular the following commits that addresses this:
- adb976da8e28ac9200bb95148c079b037dd04b39
- 682560ec1e39c656e177dbbcb93fb933008b13ef
- 5178fc425c4375097e425320c758fe6af9f5b6d2
- 8f47e9dac39292e8b58ffb3b8b46108aba7c1fc3

> 1. Should cleanup the README and make it easier to understand and read

Did some small updates to the README too. Overall still needs more loving and polish, especially the sub-pages for Vagrant, security prereqs, and Ansible.

**Comment by jamestyj** [comment]
Issue/task to improve security README in https://github.com/cloudera-ps/prereq-checks/issues/82.
