### ISSUE TITLE
Check that ntp is in sync

### ISSUE THREAD

**Issue by manojsundaram** [cloudera-ps/prereq-checks#9]
feature request: add check to see if ntp is in sync. Can do so by using "ntpstat" command.

This applies when NTP is used for time synchronization. If Chrony is used, need to find an alternate way to do this.

**Comment by jhshin9** [comment]
@manojsundaram @kmizumar I am working on this.

**Comment by jhshin9** [comment]
@kmizumar Please, review and merge. Thanks.

**Comment by jamestyj** [comment]
@kmizumar Please close this issue assuming you agree with my comments in https://github.com/cloudera-ps/prereq-checks/pull/27. Thanks.

**Comment by kmizumar** [comment]
I agree that the existing ntp sync check should be sufficient. Closing this issue without merging pull request #27
